services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: cd portfolio-api && npm install && npm run build
    startCommand: cd portfolio-api && rsync -a public/ /data/public/ && npm run start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyCfVpcvS7o1GeLq0HKe4Yy-D87JQqU-1Yo
